In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import os
os.chdir('/content/drive/MyDrive/Colab Notebooks/')

#### Downloading CallGraph_0.csv

In [ ]:

# file_id = '1l1Zebe2-r6DrL1PwbNB431RCscSu9IXz' # Replace with the actual file ID
# !gdown --id $file_id

#### Downloading MCRRT.csv

In [ ]:

# file_id = '1ynXM49k1FdyzhfrFPxnZI4_HXO8k58cy' # Replace with the actual file ID
# !gdown --id $file_id

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1ynXM49k1FdyzhfrFPxnZI4_HXO8k58cy
From (redirected): https://drive.google.com/uc?id=1ynXM49k1FdyzhfrFPxnZI4_HXO8k58cy&confirm=t&uuid=262d8128-52e6-4f11-9e8c-9893a0956840
To: /content/drive/MyDrive/Colab Notebooks/MCRRTUpdate_0.csv
100% 5.38G/5.38G [00:56<00:00, 94.7MB/s]

#### Downloading MSMetrics.csv

In [ ]:
# file_id = '1sZutUdbaWdmD3DqaNW-Zv6kjPSXD17tZ' # Replace with the actual file ID
# !gdown --id $file_id

#### Downloading NodeMetrics.csv

In [ ]:
# file_id = '1k7w6pgM9GL6F78LzBf_jgVU-i500nIkV' # Replace with the actual file ID
# !gdown --id $file_id

### Checking Directory

In [8]:
os.listdir()

['train.csv',
 'test.csv',
 '.ipynb_checkpoints',
 'covtype.csv',
 'train_dataset.csv',
 'test_dataset.csv',
 'first_500_rows.csv',
 'ML_Project (1).ipynb',
 'ML_Project.ipynb',
 'glove.6B.50d.txt',
 'NLP_Practical.ipynb',
 'Untitled0.ipynb',
 'CallGraph_0.csv',
 'MSMetricsUpdate_0.csv',
 'NodeMetricsUpdate_0.csv',
 'MSMetricsUpdate_0.csvnh4pbcoz.part',
 'MCRRTUpdate_0.csv']

### Required Modules

In [4]:
import pandas as pd

### Reading all .CSV Files
##### 1. MicroService_Metrics ---> ms_metric
##### 2. MC_RRT ---> mc_rrt
##### 3. Node Metrics ---> node_metric
##### 4. CallGraph --> callgraph

In [5]:
ms_metric = pd.read_csv('MSMetricsUpdate_0.csv',on_bad_lines='skip')

In [6]:
mc_rrt = pd.read_csv('MCRRTUpdate_0.csv',on_bad_lines='skip')

In [7]:
node_metric = pd.read_csv('NodeMetricsUpdate_0.csv',on_bad_lines='skip')

In [8]:
call_graph = pd.read_csv('CallGraph_0.csv',on_bad_lines='skip')

### Identifying Columns of 4 Files

### working_Values

In [9]:
try:
    callp = call_graph
    nodem = node_metric
    msmetric = ms_metric
    mcrrt = mc_rrt
except: 
    raise Exception("Error")

#### PreProcessing

In [10]:
callp.head(5)

,timestamp,traceid,service,rpc_id,rpctype,um,uminstanceid,interface,dm,dminstanceid,rt
0,115352,T_11560863075,S_153587416,0.1,rpc,MS_58845,MS_58845_POD_0,xOuy6-80Vt,MS_71712,MS_71712_POD_244,2.0
1,86450,T_22121589080,S_1798353,0.1,rpc,MS_24094,MS_24094_POD_3317,4Db39LxDTC,MS_24094,MS_24094_POD_5168,5.0
2,86450,T_22121589080,S_1798353,0.1,rpc,MS_24094,MS_24094_POD_983,4Db39LxDTC,MS_24094,MS_24094_POD_5168,5.0
3,155753,T_22121586395,S_85905920,0.1,rpc,MS_24094,MS_24094_POD_5463,1oNt-EK5Lm,MS_67455,MS_67455_POD_222,9.0
4,90649,T_22825688569,S_160146479,0.1.1.1,http,MS_29868,MS_29868_POD_22,XQrDXTN_dB,UNKNOWN,UNKNOWN,18.0

In [14]:
callp.shape

(13331267, 11)

In [17]:
len(callp['traceid'].notnull())

13331267

In [31]:
callp.head(5)

,timestamp,traceid,service,rpc_id,rpctype,um,uminstanceid,interface,dm,dminstanceid,rt
0,115352,T_NaN,S_153587416,0.1,rpc,MS_58845,MS_58845_POD_0,xOuy6-80Vt,MS_71712,MS_71712_POD_244,2.0
1,86450,T_NaN,S_1798353,0.1,rpc,MS_24094,MS_24094_POD_3317,4Db39LxDTC,MS_24094,MS_24094_POD_5168,5.0
2,86450,T_NaN,S_1798353,0.1,rpc,MS_24094,MS_24094_POD_983,4Db39LxDTC,MS_24094,MS_24094_POD_5168,5.0
3,155753,T_NaN,S_85905920,0.1,rpc,MS_24094,MS_24094_POD_5463,1oNt-EK5Lm,MS_67455,MS_67455_POD_222,9.0
4,90649,T_NaN,S_160146479,0.1.1.1,http,MS_29868,MS_29868_POD_22,XQrDXTN_dB,UNKNOWN,UNKNOWN,18.0

In [ ]:
nodem.head(5)

2141207

In [11]:
msmetric.head(5)

,timestamp,msname,msinstanceid,nodeid,cpu_utilization,memory_utilization
0,300000,MS_68185,MS_68185_POD_91,NODE_20236,0.172378,0.662361
1,420000,MS_25215,MS_25215_POD_372,NODE_36528,0.085708,0.432862
2,720000,MS_31285,MS_31285_POD_916,NODE_23966,0.445229,0.572093
3,780000,MS_42019,MS_42019_POD_38,NODE_34880,0.091057,0.529339
4,900000,MS_9482,MS_9482_POD_332,NODE_45529,0.177660,0.642626

In [12]:
mcrrt.head(5)

,timestamp,msname,msinstanceid,nodeid,providerrpc_rt,providerrpc_mcr,consumerrpc_rt,consumerrpc_mcr,writemc_rt,writemc_mcr,...,writedb_rt,writedb_mcr,readdb_rt,readdb_mcr,consumermq_rt,consumermq_mcr,providermq_rt,providermq_mcr,http_mcr,http_rt
0,60000,MS_49464,MS_49464_POD_4,NODE_41256,0.000000,0.000000,5.346655,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,4.96123,0.000155,1.344713,0.000071,1.865916e-07,0.083333
1,120000,MS_66860,MS_43316_POD_3,NODE_36486,6.257353,0.000001,0.000000,7.869866e-13,0.0,0.0,...,1.911765,0.000002,0.442857,0.000002,0.00000,0.000000,0.000000,0.000000,1.767710e-07,0.250000
2,60000,MS_4951,MS_4951_POD_7,NODE_46562,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,8.249315e-07,455.847785
3,120000,MS_42505,MS_20844_POD_104,NODE_30733,0.000000,0.000000,32.523810,0.000000e+00,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
4,60000,MS_73317,MS_73317_POD_1797,NODE_3619,10.119451,0.000012,9.996974,7.169679e-12,0.0,0.0,...,0.000000,0.000000,0.969355,0.000006,0.00000,0.000000,24.421801,0.000002,0.000000e+00,0.000000